### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by Manuel-S** [adamralph/dude#10]
Hey, is this still active?

I've been looking for a standalone csi.exe alternative with a chocolatey installer.

Would you consider publishing there?

**Comment by adamralph** [comment]
Hi @Manuel-S, no this project is no longer active. These days I download the [`Microsoft.Net.Compilers` NuGet package](https://www.nuget.org/packages/Microsoft.Net.Compilers/) and execute `tools\csi.exe`.

Would you like to take over the project? I can transfer it to you if you like.

**Comment by Manuel-S** [comment]
In that case I would prefer to just make a chocolatey package that downloads and installs csi.exe from that nuget package, but thanks :)
